# Generated by Django 3.0.5 on 2020-05-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Co2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True)),
                ('value', models.IntegerField(blank=True)),
            ],
            options={
                'db_table': 'co2',
            },
        ),
    ]
