# Generated by Django 3.0.5 on 2020-05-02 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='co2',
            old_name='value',
            new_name='co2_rate',
        ),
    ]
