# Generated by Django 3.0.5 on 2020-05-03 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_auto_20200502_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='co2',
            name='co2_rate',
        ),
        migrations.RemoveField(
            model_name='co2',
            name='datetime',
        ),
        migrations.AlterModelTable(
            name='co2',
            table=None,
        ),
    ]
