# Generated by Django 3.0.5 on 2020-05-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_auto_20200503_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='co2',
            name='co2_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='co2',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='co2',
            table='co2',
        ),
    ]
