# Generated by Django 3.0.5 on 2020-05-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_auto_20200503_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='co2',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
